-- 테이블 포맷변경
ALTER TABLE DC_BOARD_JOB_TB MODIFY (STARTTIME VARCHAR2(5));
ALTER TABLE DC_BOARD_JOB_TB MODIFY (ENDTIME VARCHAR2(5));

-- 회원정보 입력
-- 회원번호 / 이메일 / 닉네임 / 비밀번호 / 가입일 / 포인트 / 지역번호 / 권한번호 / 주소 / 이름
INSERT INTO DC_MEMBER_TB VALUES (SEQ_MEMBER.NEXTVAL, 'admin@admin.com', 'admin', 1234, sysdate, 0, 1, 1, 'STATUS001', '영등포구', '관리자');

-- 업체정보 등록
-- 업체번호 / 업체명 / 등록일 / 주소 / 상태
INSERT INTO DC_COMPANY_TB VALUES(SEQ_COMPANY.NEXTVAL, '외길편의점', '2018/06/27', '서울 강남구 역삼동 테헤란로', 'STATUS020');
INSERT INTO DC_COMPANY_TB VALUES(SEQ_COMPANY.NEXTVAL, '외길돈까스', '2018/06/28', '서울 강남구 역삼동 테헤란로', 'STATUS021');
INSERT INTO DC_COMPANY_TB VALUES(SEQ_COMPANY.NEXTVAL, '외길파스타', '2018/06/29', '서울 강남구 역삼동 테헤란로', 'STATUS021');
INSERT INTO DC_COMPANY_TB VALUES(SEQ_COMPANY.NEXTVAL, '외길돈부리', '2018/06/30', '서울 강남구 역삼동 테헤란로', 'STATUS022');
INSERT INTO DC_COMPANY_TB VALUES(SEQ_COMPANY.NEXTVAL, '외길감자탕', '2018/06/30', '서울 강남구 역삼동 테헤란로', 'STATUS023');

-- 등록업체정보
SELECT NO, NAME, ENROLLDATE, ADDRESS, VALUE
FROM DC_COMPANY_TB C
JOIN DC_CODE_TB CD ON(CD.ID = C.STATUS);

-- BOARD 추가
-- 게시글번호 / 게시글제목 / 작성 / 게시글내용 / 조회수 / 게시판유형 / 게시글상태 / 회원번호 / 자유게시판 카테고리
INSERT INTO DC_BOARD_TB VALUES(
    SEQ_BOARD.NEXTVAL, '구인합니다', SYSDATE, '이 구인은 17세기 영국으로부터 시작되어', 0, 'BOARD006', 'STATUS001', 1, NULL);

-- 추가확인
SELECT * FROM DC_BOARD_TB;

-- BOARD 구인구직테이블 추가
-- 구인구직게시글번호 / 구인구직구분 / 급여 / 
-- 게시글 시작일 / 게시글 마감일 / 근무 시작일 / 근무 종료일 /
-- 근무시작시간 / 근무종료시간 / 근무장소 / 게시글번호 /
-- 업체번호 / 고용타입 / 봉급타입 / 구인구직상태
INSERT INTO DC_BOARD_JOB_TB VALUES(
    SEQ_BOARD_JOB.NEXTVAL, 'JTYPE001', 5000, 
    SYSDATE, '2019/01/01', SYSDATE, '2019/01/01',  
    '10:30', '20:00', '서울시 강남구 역삼동', 5, 
    3, 'JOBTYPE001', 'SALTYPE001', 'STATUS001');

-- 추가확인
SELECT * FROM DC_BOARD_JOB_TB B;

-- 게시판  + 구인구직테이블 조회
SELECT JB.NO, TITLE, NICKNAME, WRITEDATE, STARTDATE, ENDDATE, STARTJOB, ENDJOB, SALARY, CD1.VALUE, CD2.VALUE, VIEWCOUNT
FROM DC_BOARD_TB B
JOIN DC_BOARD_JOB_TB JB ON(JB.BOARDNO = B.NO)
JOIN DC_MEMBER_TB M ON(M.NO = B.MEMBERNO)
JOIN DC_CODE_TB CD1 ON(CD1.ID = JB.SALTYPE)
JOIN DC_CODE_TB CD2 ON(CD2.ID = JB.JOBTYPE);

-- 마감 D-DAY
SELECT FLOOR(ENDDATE - SYSDATE)
FROM DC_BOARD_JOB_TB
WHERE BOARDNO = 5;

-- 근무시간
SELECT SUBSTR(ENDTIME, 1, 2) - SUBSTR(STARTTIME, 1, 2) HOUR, SUBSTR(ENDTIME, 4, 2) - SUBSTR(STARTTIME, 4, 2) MIN
FROM DC_BOARD_JOB_TB
WHERE BOARDNO = 5;


SELECT SUBSTR(ENDTIME, 1, 2) - SUBSTR(STARTTIME, 1, 2) HOUR, SUBSTR(ENDTIME, 4, 2) - SUBSTR(STARTTIME, 4, 2) MIN
CASE WHEN MIN > 0 THEN HOUR + 1
FROM DC_BOARD_JOB_TB     
WHERE BOARDNO = 5;

